// <auto-generated />
using System;
using DAL_DataAccessLayer.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL_DataAccessLayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20211107104922_dung2")]
    partial class dung2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL_DataAccessLayer.Models.ChuTro", b =>
                {
                    b.Property<int>("MaChuTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChucVu")
                        .HasColumnType("int");

                    b.Property<int?>("ChucVusMaChucVu")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NamSinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SDT")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaChuTro");

                    b.HasIndex("ChucVusMaChucVu");

                    b.ToTable("ChuTro");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.ChucVu", b =>
                {
                    b.Property<int>("MaChucVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TenChucVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaChucVu");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.DichVu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LoaiDichVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenDichVu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.DichVuChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ChiSoCu")
                        .HasColumnType("int");

                    b.Property<int>("ChiSoMoi")
                        .HasColumnType("int");

                    b.Property<int?>("DichVusId")
                        .HasColumnType("int");

                    b.Property<string>("DonGia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DichVusId");

                    b.ToTable("DichVuChiTiet");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HinhAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HinhAnhPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PhongTrosMaPhongTro")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhongTrosMaPhongTro");

                    b.ToTable("HinhAnh");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HopDong", b =>
                {
                    b.Property<int>("MaHopDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ChuTrosMaChuTro")
                        .HasColumnType("int");

                    b.Property<int?>("KhachHangsMaKhachHang")
                        .HasColumnType("int");

                    b.Property<string>("TongTien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaHopDong");

                    b.HasIndex("ChuTrosMaChuTro");

                    b.HasIndex("KhachHangsMaKhachHang");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HopDongChiTiet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("DichVuChiTietsId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("HopDongsMaHopDong")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayXuat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TienDien")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienMang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienNuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienVeSinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DichVuChiTietsId");

                    b.HasIndex("HopDongsMaHopDong");

                    b.ToTable("HopDongChiTiet");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.KhachHang", b =>
                {
                    b.Property<int>("MaKhachHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("GioiTinh")
                        .HasColumnType("int");

                    b.Property<int>("MaPhongTro")
                        .HasColumnType("int");

                    b.Property<string>("QueQuan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhachHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TienCoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaKhachHang");

                    b.ToTable("KhachHang");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.LoaiPhong", b =>
                {
                    b.Property<int>("MaLoaiPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("HopDongMaHopDong")
                        .HasColumnType("int");

                    b.Property<string>("TenLoaiPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaLoaiPhong");

                    b.HasIndex("HopDongMaHopDong");

                    b.ToTable("LoaiPhong");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.PhongTro", b =>
                {
                    b.Property<int>("MaPhongTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DiaChi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DienTich")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GiaPhong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HopDongsMaHopDong")
                        .HasColumnType("int");

                    b.Property<int?>("LoaiPhongsMaLoaiPhong")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("MaPhongTro");

                    b.HasIndex("HopDongsMaHopDong");

                    b.HasIndex("LoaiPhongsMaLoaiPhong");

                    b.ToTable("PhongTro");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.ChuTro", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.ChucVu", "ChucVus")
                        .WithMany("ChuTros")
                        .HasForeignKey("ChucVusMaChucVu");

                    b.Navigation("ChucVus");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.DichVuChiTiet", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.DichVu", "DichVus")
                        .WithMany("DichVuChiTiets")
                        .HasForeignKey("DichVusId");

                    b.Navigation("DichVus");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HinhAnh", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.PhongTro", "PhongTros")
                        .WithMany("HinhAnhs")
                        .HasForeignKey("PhongTrosMaPhongTro");

                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HopDong", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.ChuTro", "ChuTros")
                        .WithMany("HopDongs")
                        .HasForeignKey("ChuTrosMaChuTro");

                    b.HasOne("DAL_DataAccessLayer.Models.KhachHang", "KhachHangs")
                        .WithMany("HopDongs")
                        .HasForeignKey("KhachHangsMaKhachHang");

                    b.Navigation("ChuTros");

                    b.Navigation("KhachHangs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HopDongChiTiet", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.DichVuChiTiet", "DichVuChiTiets")
                        .WithMany("HopDongChiTiets")
                        .HasForeignKey("DichVuChiTietsId");

                    b.HasOne("DAL_DataAccessLayer.Models.HopDong", "HopDongs")
                        .WithMany("HopDongChiTiets")
                        .HasForeignKey("HopDongsMaHopDong");

                    b.Navigation("DichVuChiTiets");

                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.LoaiPhong", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.HopDong", null)
                        .WithMany("LoaiPhongs")
                        .HasForeignKey("HopDongMaHopDong");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.PhongTro", b =>
                {
                    b.HasOne("DAL_DataAccessLayer.Models.HopDong", "HopDongs")
                        .WithMany()
                        .HasForeignKey("HopDongsMaHopDong");

                    b.HasOne("DAL_DataAccessLayer.Models.LoaiPhong", "LoaiPhongs")
                        .WithMany("PhongTros")
                        .HasForeignKey("LoaiPhongsMaLoaiPhong");

                    b.Navigation("HopDongs");

                    b.Navigation("LoaiPhongs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.ChuTro", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.ChucVu", b =>
                {
                    b.Navigation("ChuTros");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.DichVu", b =>
                {
                    b.Navigation("DichVuChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.DichVuChiTiet", b =>
                {
                    b.Navigation("HopDongChiTiets");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.HopDong", b =>
                {
                    b.Navigation("HopDongChiTiets");

                    b.Navigation("LoaiPhongs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.KhachHang", b =>
                {
                    b.Navigation("HopDongs");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.LoaiPhong", b =>
                {
                    b.Navigation("PhongTros");
                });

            modelBuilder.Entity("DAL_DataAccessLayer.Models.PhongTro", b =>
                {
                    b.Navigation("HinhAnhs");
                });
#pragma warning restore 612, 618
        }
    }
}
